name: release
on:
  push:
    branches: [ main ]
jobs:
  test-and-release-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node and npm
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - run: npm i
      - run: npm run test